### ISSUE TITLE
The update C model has a little difference with the paper. 

### ISSUE THREAD

**Issue by epilos** [lpcccc-cv/MC-VarNet#1]
I can not find the simple feature transformation layer (FTL) in your code. The way to update C in your code is much easier, can you explain why the C can be update in this way?

**Comment by lpcccc-cv** [comment]
We use simple convolutional layers to realize the feature transformation operations. In our code, the E_c and D_c denotes two feature transformation layers for C, E_c is used to transform C from image domain to feature domain, and D_c transform from feature to image domain.

**Comment by epilos** [comment]
![image](https://github.com/lpcccc-cv/MC-VarNet/assets/135088040/589c4c27-26b5-4212-b310-ea6cc2d691fe)
yep， but in this function, $E_c$ should not appear.Besides, as  you said in the article, the $E_c$ opearator is Encoder CDic layer.
![image](https://github.com/lpcccc-cv/MC-VarNet/assets/135088040/e35f8fc4-7433-438f-87c1-946a6366cbf4)
I don't find the $\tau_c$ in your code, and I think this code is different from the formula in the article.

**Comment by lpcccc-cv** [comment]
Thank you for reminding us. We have checked the code again and found that the version we uploaded was wrong. We will upload the correct version as soon as possible.

**Comment by lpcccc-cv** [comment]
> ![image](https://github.com/lpcccc-cv/MC-VarNet/assets/135088040/589c4c27-26b5-4212-b310-ea6cc2d691fe) yep， but in this function, Ec should not appear.Besides, as you said in the article, the Ec opearator is Encoder CDic layer. ![image](https://github.com/lpcccc-cv/MC-VarNet/assets/135088040/e35f8fc4-7433-438f-87c1-946a6366cbf4) I don't find the τc in your code, and I think this code is different from the formula in the article.

We've reuploaded our code and thank you for your attention！
