### ISSUE TITLE
您好，我想问下数据集的问题，是要自己先按照7：1：2分好再进行nii转png吗？然后文章中提到了用IXI数据集用PD作为参考，但在代码中在哪使用PD了呢？

### ISSUE THREAD

**Issue by tututututurana** [lpcccc-cv/MC-VarNet#6]

**Comment by lpcccc-cv** [comment]
1、划分数据集最好先划分nii
2、PD代码位置
https://github.com/lpcccc-cv/MC-VarNet/blob/c803aad4d5c157e3111441588dab81219a28b9db/data/IXI_dataset.py#L125
